config/routes.rb
FakeTwitterOnRails::Application.routes.draw do
  root :to => "home#index"
  resources :user do
    resources :followings 
    resources :tweet 
  end

  get "log_in" => "sessions#new", :as => "log_in" 
  get "log_out" => "sessions#destroy", :as => "log_out"
  post "log_in" => "sessions#create"
  resources :sessions
end

app/models/following.rb
class Following < ActiveRecord::Base
  belongs_to :user
  belongs_to :follower, :class_name => "User" 
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user

  def self.search(search)
    if search 
      find(:all, :conditions => ['name LIKE ?', "%#{search}"])
    else
      find(:all)
    end
  end

end

app/models/user.rb
require 'gravtastic'

class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password

  validates_uniqueness_of(:email, :message => "Someone already has this email, try another.")
  validates_uniqueness_of(:user_name, :message => "This user name is already taken.")

  validates_presence_of(:first_name)
  validates_presence_of(:last_name)
  validates_presence_of(:state)
  validates_presence_of(:city)
  validates_presence_of(:bio)
  validates_presence_of(:password)


  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)

    end
  end



  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def self.search(search)
    if search 
      find(:all, :conditions => ['first_name LIKE ?', "%#{search}"])
    end
  end

  include Gravtastic
  gravtastic

  has_many :tweets
  has_many :followings
  has_many :followers, :through => :followings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

helper_method :current_user

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/following_controller.rb
class FollowingController
  def index
  end

  def new
  end

  def create
    @following = Following.new(following_params)
      if @following.save
        flash[:notice] = "You're now following #User.find({@following.follower_id})"
      else
        flash[:notice] = "There was a problem"
      end
  end

  def edit
  end

  def update
  end

  def destroy
  end

private

  def following_params
    params.require(:following).permit(:user_id, :follower_id)
  end


end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  def index
  end

  def new
  end

  def create
    @user = User.find(session[:user_id])
    @following = Following.new(user_id: session[:user_id], follower_id: params[:user_id])
      if @following.save && @user.followings << @following
        flash[:notice] = "You're now following #{User.find(@following.follower_id).user_name}"
      else
        flash[:notice] = "There was a problem"
      end
      redirect_to user_path(@user)
  end

  def edit
  end

  def update
  end

  def destroy
  end

private

  def following_params
    params.require(:follow).permit(:user_id, :follower_id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if !current_user.nil?
      @user = User.find(session[:user_id])
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user 
      session[:user_id] = user.id
      redirect_to user_path(user.id), :notice => "You're logged in!"
    else
      flash.now.alert = "You're email and/or password were invalid"
      render "new"
    end
  end

 def destroy
  session[:user_id] = nil
  flash[:notice] = "You've signed out"
  redirect_to root_path
 end

end

app/controllers/tweet_controller.rb
class TweetController < ApplicationController
  def new
    @user = User.find(params[:user_id])
  end

  def create
    @user = User.find(params[:user_id])
    @tweet = Tweet.new(tweet_params)
      if @tweet.save && @user.tweets << @tweet
        flash[:notice] = "Your tweet was successfully saved!"
      else
        flash[:notice] = "There was an error saving your tweet."
      end
      redirect_to user_path(@user)
  end

  def edit
    @user = User.find(params[:user_id])
    @tweet = Tweet.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @tweet = Tweet.find(params[:id])
  end

  def index

  end

  def destroy
    @tweet.find(params[:id])
    @tweet.destroy
    redirect_to user_path
  end

  private
  def tweet_params
    params.require(:tweet).permit(:text)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.id = session[:user_id]
      flash[:notice] = "Your account was created!"
      redirect_to user_path(@user)
    else
      flash[:notice] = "There was a problem creating your account"
      redirect_to new_user_path
    end
  end

  def edit 
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.save
      flash[:notice] = "Your account was created!"
    else
      flash[:notice] = "There was a problem creating your account"
    end
    redirect_to root_path

  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "User was destroyed."
    else
      flash[:notice] = "There was a problem destroying the user."
    end
    redirect_to user_index_path
  end

  def show
    @user = User.find(params[:id])
    @following = Following.new
  end

  def index
    @users = User.search(params[:search])
  end


  private

  def user_params
    params.require(:user).permit(:email, :password, :first_name, :last_name, :bio, :user_name, :city, :state)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.haml
%h1 
  Fake Twitter
-if !current_user.nil?
  %h4
    Hi #{@user.user_name}! Here's whats happening.
  -if !@user.followings.nil? 
    -@user.followings.each do |following|
      %h4
        =User.find(following.follower_id).user_name
      -User.find(following.follower_id).tweets.each do |tweet|
        =tweet.text
        %br
        =tweet.created_at.strftime("%B %d, %Y at %I:%M %p")
        %br
        %br
      %br
  -else
    %h4
      Search for some people to follow using the form!

app/views/layouts/application.haml
!!!
%html
  %head
    %title FakeTwitterOnRails
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = stylesheet_link_tag "bootstrap.min"
    = csrf_meta_tags

  .col-lg-offset-4
    .containter
      %body
      %br
        %ul.nav.nav-pills
          %li
            =link_to "Home", root_path
          -if !current_user.nil?
            %li
              =link_to "Profile", user_path(current_user)
          -if current_user.nil?
            %li
              =link_to "Sign In", log_in_path
            %li
              =link_to "Sign Up", new_user_path
          -if !current_user.nil?
            %li
              =link_to "Sign Out", log_out_path
      - if flash[:error]
        %p.error= h flash[:error]
      - if flash[:notice]
        %p.notice= h flash[:notice]
      %div
        = yield
      -if !current_user.nil?
        %br
        %br
        %footer
          =form_tag user_index_path, :method => 'get' do
            %p 
              =text_field_tag :search, params[:search]
              =submit_tag "Search for Users", :name => nil

app/views/tweet/new.haml
%h1  
  New Tweet
=form_for Tweet.new, :url => user_tweet_index_path(@user) do |f|
  =f.text_area :text
  =f.submit

app/views/user/_form.haml
#commentForm
  .form-horizontal
    Fake Twitter uses Gravatar, get yours 
    %a{:href => "http://en.gravatar.com/", :target => "blank"} here
    %br
    =f.label :email
    =f.text_field :email
    %br
    %br
  .form-horizontal
    =f.label :user_name
    =f.text_field :user_name
    %br
    %br
  .form-horizontal
    =f.label :password
    =f.password_field :password
    %br
    %br
  .form-horizontal
    =f.label :password_confirmation
    =f.password_field :password_confimation
    %br
    %br
  .form-horizontal
    =f.label :bio
    =f.text_area :bio
    %br
    %br
  =f.submit "Sign Up!"

app/views/user/index.haml
-if !@users.nil?
  %h1 
    Search
  -@users.each do |user|
    %h3
      %a{:href => 'user/' + user.id.to_s} 
        =user.first_name + " " + user.last_name
    %h3
      Bio
    =user.bio
    %br
    %h3
      Tweets
    -user.tweets.each do |tweet|
      =tweet.text
      %br
      =tweet.created_at.strftime("%B %d, %Y at %I:%M %p")
      %br
      %br
-else
  %h1
    Sorry no results, please search again.

app/views/user/new.haml
%h1 Sign Up For Fake Twitter using Rails
=form_for @user, :url => user_index_path do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @model.errors.full_messages.each do |msg|
          %li= msg
  =render "form", {f: f}
  

app/views/user/show.haml
-if current_user == @user
  %h1
    =@user.user_name
  %img{:src => @user.gravatar_url}
  %h3
    Your Tweets
  -@user.tweets.each do |tweet|
    =tweet.text
    %br
    =tweet.created_at.strftime("%B %d, %Y at %I:%M %p")
    %br
    %br
  -if !@user.followings.nil?
    %h3
      News Feed
    -@user.followings.each do |following|
      =User.find(following.follower_id.to_s).first_name

  %h3 
    New Tweet
  =form_for Tweet.new, :url => user_tweet_index_path(@user) do |f|
    =f.text_area :text
    %br
    %br
    =f.submit
-elsif !current_user.nil? 
  %h1
    =@user.user_name
  =button_to 'Follow', {:controller => "followings", :action => "create", :user_id => @user.id, :follower_id => session[:user_id]}, :method => :post

  %br
  -@user.tweets.each do |tweet|
    =tweet.text
    %br
    =tweet.created_at.strftime("%B %d, %Y at %I:%M %p")
    %br
    %br
-else
  %h1
    =@user.user_name
  %h3
    Tweets
  -@user.tweets.each do |tweet|
    =tweet.text
    %br
    =tweet.created_at.strftime("%B %d, %Y at %I:%M %p")
    %br
    %br